#!/usr/bin/zsh

# Search DuckDuckGo via Unduck

query="$*"
if [[ -z "$query" ]]; then
    read -r "query?Search Unduck: "
    [[ -z "$query" ]] && exit 1
fi

url="https://unduck.link/?q=$query"

if [[ -n "$WSL_DISTRO_NAME" ]]; then
    wsl-browser auto "$url"
elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url"
elif command -v open >/dev/null 2>&1; then
    open "$url"
elif [[ -n "$BROWSER" ]]; then
    $BROWSER "$url"
else
    echo "[ERROR] No suitable method found to open URLs." >&2
    exit 1
fi
