#!/usr/bin/env bash

set -euo pipefail

git rev-parse --is-inside-work-tree &>/dev/null || exit 1

if [[ $(git rev-list --count HEAD) -le 1 ]]; then
    echo "Already at the first commit"
    exit 0
fi

git checkout HEAD~1
