#!/bin/bash

if [[ -z "$WSL_DISTRO_NAME" ]]; then
    echo "This script is intended to be run under WSL." >&2
    exit 1
fi

EDGE_WINDOW_PATH="/mnt/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
if [[ ! -f "$EDGE_WINDOW_PATH" ]]; then
    [[ "$1" == "--check" ]] && exit 1
    echo "Edge is not installed in the expected location: $EDGE_WINDOW_PATH" >&2
    exit 1
fi
[[ "$1" == "--check" ]] && exit 0

URL="$1"
if [[ ! ("$URL" =~ ^/ && -f "$URL") ]]; then
    exec "$EDGE_WINDOW_PATH" "$URL"
fi

WINDOWS_TEMP="/mnt/c/Temp"
mkdir -p "$WINDOWS_TEMP"

FILENAME=$(basename "$URL")
cp "$URL" "$WINDOWS_TEMP/$FILENAME"

exec "$EDGE_WINDOW_PATH" "file:///C:/Temp/$FILENAME"
