[mgr]
show_hidden = false
show_symlink = false
sort_by = "mtime"

[opener]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" }
]
view = [
    { run = 'imv "$@"', orphan = true, for = "unix" }
]

[open]
rules = [
    { name = "*/", use = "folder" },
    { mime = "image/*", use = "view" },
    { mime = "video/*", use = "play" },
    { mime = "audio/*", use = "play" },
]
