daemon:
  modules:
  - Xim
  - Wayland
  - Indicator
indicator:
  icon_color: Black
log:
  global_level: DEBUG
engine:
  translation_layer: null
  default_category: Latin
  global_category_state: false
  global_hotkeys:
    C-Space:
      behavior: !Toggle
        - Hangul
        - Latin
      result: Consume
    Esc:
      behavior: !Switch Latin
      result: Bypass
  category_hotkeys:
    Hangul:
      Hangul:
        behavior: !Mode Hanja
        result: ConsumeIfProcessed
  mode_hotkeys:
    Math:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Hanja:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Emoji:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
  candidate_font: Noto Sans CJK KR
  xim_preedit_font:
  - Noto Sans CJK KR
  - 15.0
  latin:
    layout: Qwerty
    preferred_direct: true
  hangul:
    layout: sebeolsik-3-90
    word_commit: false
    preedit_johab: Needed
    layout_addons:
      all:
      - ComposeJungseongSsang
      - ComposeChoseongSsang
      - FlexibleComposeOrder
